### ISSUE TITLE
RJP MultiURLs not converting when inside an archetype

### ISSUE THREAD

**Issue by Lachlann** [micklaw/Ditto.Resolvers#15]
Hello, 
When i have a RJP MultiURL picker as a property in my Archetype it does not seem to get converted and instead returns null, Here is my model for my archetpye

`    [ArchetypeContent]
    public class PlainTextImageLink
    {
        public string Title { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public MultiUrls Link { get; set; }
    }`

When i set the type of Link to be a string I can see the JSON data output in the front end however the convertor does not seem to work. Any ideas? am i missing something
Best
L

**Comment by micklaw** [comment]
Hey man,

Sorrry, I might need a bit of background here and some refresher time for me (Sorry, its been a while since I've looked at this product :)). Totally harbouring a guess that RJP is a package or something which returns a JSON string of a link object which you are attempting to deserialise to the type **MultiUrls**?

In this instance, and making the assumption that the type **PlainTextImageLink** is the POCO mapping to the Archetype, you should have to define your Archetype class something like this:

```csharp
public class PlainTextImageLink 
{ 
        public string Title { get; set; } 
        public string Text { get; set; } 
        public string Image { get; set; } 
        [TypeConverter(typeof(YourRJDTypeConverter))]
        public MultiUrls Link { get; set; }
 }
```

Notice you dont need the **ArchetypeContent]**, this is only required if you are using a MultiFieldset Archetype and require your collection to have its generic type to be an abstract type. Instead you should decorate the **PlainTextImageLink** property on your Ditto POCO with an **ArchetypeValueResolver** attribute.

Natively this application only attempts to convert properties in an Archetype where the POCO property type has an existing .Net TypeConverters for converting strings to some common types (decimal, int, string etc), reference types.Most reference Types require custom TypeConverters to be made, so your **MultiUrls ** POCO would require its own TypeConverter to be made to allow for our source to know how to convert the JSON to your Type. This is why you can see it assigns the value when its a string but default(T)'s when its a reference Type.

**DISCLAIMER**: I must say man, I am not really recommending this approach if using a new site or the new version of Ditto. Ditto uses processors now and also has a polymorphic processor called something like **FactoryProcessor** or something. This code (while obviously totally awesome) should be considered only to be used on older versions of Ditto, defo use the new stuff where possible.

Hope this helps dude.

**Comment by Lachlann** [comment]
Hey!,
Firstly sorry for my crappy question i had to run off and deal with a crying baby :)  you nailed it in your response though. 
I have removed the resolver and have gone with the newer Ditto Processors. For anyone else looking at this I found this comment very useful in setting up a multi-block processor:

https://github.com/leekelleher/umbraco-ditto/issues/168#issuecomment-230558415

Thanks again!
